#!/bin/sh -xe
#
# Ensure /usr/src and /usr/xenocara is up to date
# before running this script.

upgradekernel() {
	cd /usr/src/sys/arch/`uname -m`/conf
	config GENERIC.MP
	cd /usr/src/sys/arch/`uname -m`/compile/GENERIC.MP
	make clean
	make
	make install
	chmod 644 /bsd
	# might have to reboot at this stage, check out
	# http://www.openbsd.org/faq/current.html
}

upgradeworld() {
	rm -rf /usr/obj/*
	cd /usr/src
	make clean
	make obj
	cd /usr/src/etc && env DESTDIR=/ make distrib-dirs
	cd /usr/src
	make build
}

upgradexenocara() {
	rm -rf /usr/xobj/*
	cd /usr/xenocara
	make clean
	make bootstrap
	make obj
	make build
}

finish() {
	cd /dev
	cp /usr/src/etc/etc.`machine`/MAKEDEV ./
	./MAKEDEV all
	sysmerge
	fw_update
}

upgradekernel
#upgradeworld
#upgradexenocara
#finish
